In [1]:
import json
import pandas as pd

# Load the JSON file as a string
with open('airlines-1558527599826.json', 'r') as f:    #only the first JSON file 
    json_str = f.read()

# Split the string into a list of JSON objects
json_objs = json_str.split('\n')

# Parse each JSON object in the list and append to a list of dictionaries
dict_list = []
for json_obj in json_objs:
    if json_obj.strip() == '':
        continue
    dict_list.append(json.loads(json_obj))

# Convert the list of dictionaries to a Pandas DataFrame
df = pd.DataFrame(dict_list)
df

,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,filter_level,lang,timestamp_ms,retweeted_status,extended_tweet,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,delete
0,Wed May 22 12:20:00 +0000 2019,1.131173e+18,1131172858951024641,La ruta de easyJet entre Londres y Menorca tra...,"[0, 113]","<a href=""https://about.twitter.com/products/tw...",False,NaN,None,NaN,...,low,es,1558527600406,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wed May 22 12:20:01 +0000 2019,1.131173e+18,1131172864147808257,RT @bttr_as1: @goody_tracy Hereâ€™s a list of so...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,...,low,en,1558527601645,{'created_at': 'Tue May 21 19:43:11 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
2,Wed May 22 12:20:02 +0000 2019,1.131173e+18,1131172867985485824,@British_Airways,NaN,"<a href=""http://twitter.com/download/android"" ...",False,1.131033e+18,1131032916232826881,3.943766e+08,...,low,und,1558527602560,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wed May 22 12:20:12 +0000 2019,1.131173e+18,1131172909463027720,RT @TheRaceRadio: Nice change by @AmericanAir....,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,...,low,en,1558527612449,{'created_at': 'Wed May 22 02:53:26 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
4,Wed May 22 12:20:28 +0000 2019,1.131173e+18,1131172975682605058,RT @sandeeprrao1991: BREAKING:-\nKLM to fly 3x...,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",False,NaN,None,NaN,...,low,en,1558527628237,{'created_at': 'Wed May 22 12:10:24 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14384,Thu May 23 11:42:26 +0000 2019,1.131526e+18,1131525791429402625,@yvettetravel were you invited to attend this?,NaN,"<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,3.046262e+08,...,low,en,1558611746066,NaN,NaN,1.131507e+18,1131507203486175237,{'created_at': 'Thu May 23 10:28:34 +0000 2019...,"{'url': 'https://t.co/iLnuh7ejub', 'expanded':...",NaN
14385,Thu May 23 11:42:27 +0000 2019,1.131526e+18,1131525795804045312,RT @RoyalFamily: The Queen sees how the @Briti...,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",False,NaN,None,NaN,...,low,en,1558611747109,{'created_at': 'Thu May 23 11:13:08 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
14386,Thu May 23 11:42:27 +0000 2019,1.131526e+18,1131525797313949698,@RoyalSpectator @British_Airways She looks AMA...,"[33, 60]","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",False,1.131512e+18,1131512419417808897,1.590887e+09,...,low,en,1558611747469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14387,Thu May 23 11:42:35 +0000 2019,1.131526e+18,1131525832500031490,@maj_fox @British_Airways Should happen more o...,"[26, 94]","<a href=""http://twitter.com/download/android"" ...",False,1.131484e+18,1131484109212196864,1.085556e+18,...,low,en,1558611755858,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14388,Thu May 23 11:42:44 +0000 2019,1.131526e+18,1131525868495474688,@British_Airways delayed 5hrs on flight BA0103...,NaN,"<a href=""http://twitter.com/download/iphone"" r...",True,NaN,None,1.833219e+07,...,low,en,1558611764440,NaN,{'full_text': '@British_Airways delayed 5hrs o...,NaN,NaN,NaN,NaN,NaN

In [3]:
column_names = df.columns.tolist()
column_names

['created_at',
 'id',
 'id_str',
 'text',
 'display_text_range',
 'source',
 'truncated',
 'in_reply_to_status_id',
 'in_reply_to_status_id_str',
 'in_reply_to_user_id',
 'in_reply_to_user_id_str',
 'in_reply_to_screen_name',
 'user',
 'geo',
 'coordinates',
 'place',
 'contributors',
 'is_quote_status',
 'quote_count',
 'reply_count',
 'retweet_count',
 'favorite_count',
 'entities',
 'extended_entities',
 'favorited',
 'retweeted',
 'possibly_sensitive',
 'filter_level',
 'lang',
 'timestamp_ms',
 'retweeted_status',
 'extended_tweet',
 'quoted_status_id',
 'quoted_status_id_str',
 'quoted_status',
 'quoted_status_permalink',
 'delete']

In [20]:
#df.to_excel(r'C:\Users\20203035\OneDrive - TU Eindhoven\Desktop\Real work\Year1-Q4\DBL challenge\dataframe.xlsx', index=False)

In [22]:
import json
import pandas as pd

# Load the JSON file as a string
with open('airlines-1558546003827.json', 'r') as f:    #only the first JSON file 
    json_str = f.read()

# Split the string into a list of JSON objects
json_objs = json_str.split('\n')

# Parse each JSON object in the list and append to a list of dictionaries
dict_list = []
for json_obj in json_objs:
    if json_obj.strip() == '':
        continue
    dict_list.append(json.loads(json_obj))

# Convert the list of dictionaries to a Pandas DataFrame
df2 = pd.DataFrame(dict_list)
df2

,created_at,id,id_str,text,display_text_range,source,truncated,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,timestamp_ms,extended_tweet,possibly_sensitive,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status,quoted_status_permalink,extended_entities,delete
0,Wed May 22 17:26:43 +0000 2019,1.131250e+18,1131250045985050624,@DaveWallsworth @kenters55 @yvrairport @Britis...,"[91, 113]","<a href=""http://twitter.com/#!/download/ipad"" ...",False,1.131238e+18,1131237948857475072,4.241206e+08,...,1558546003229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wed May 22 17:26:52 +0000 2019,1.131250e+18,1131250086355329029,.@americanair cuts surfboard fees to $30 - con...,NaN,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",True,NaN,None,NaN,...,1558546012854,{'full_text': '.@americanair cuts surfboard fe...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wed May 22 17:26:53 +0000 2019,1.131250e+18,1131250089320681472,"@AmericanAir my flight (2800, LAX to BOS) toni...",NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",True,NaN,None,2.253606e+07,...,1558546013561,"{'full_text': '@AmericanAir my flight (2800, L...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wed May 22 17:26:55 +0000 2019,1.131250e+18,1131250095662481408,RT @DavidMaTuer: Quand je roule jâ€™entends des ...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,...,1558546015073,NaN,NaN,{'created_at': 'Wed May 22 07:03:04 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
4,Wed May 22 17:26:55 +0000 2019,1.131250e+18,1131250099294810113,@AmericanAir I guess not! And the gate agent c...,"[13, 140]","<a href=""http://twitter.com/download/iphone"" r...",True,1.131248e+18,1131247521949466627,2.253606e+07,...,1558546015939,{'full_text': '@AmericanAir I guess not! And t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14134,Thu May 23 14:54:29 +0000 2019,1.131574e+18,1131574125619765251,#Supersonic blast from the past - #Concorde at...,"[0, 103]","<a href=""http://twitter.com/download/iphone"" r...",False,NaN,None,NaN,...,1558623269835,NaN,False,NaN,NaN,NaN,NaN,NaN,"{'media': [{'id': 1131574070632439808, 'id_str...",NaN
14135,Thu May 23 14:54:32 +0000 2019,1.131574e+18,1131574135015006209,RT @Irelandwest: Good news 4 sun lovers as @Ry...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,...,1558623272075,NaN,NaN,{'created_at': 'Thu May 23 12:30:12 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN
14136,Thu May 23 14:54:33 +0000 2019,1.131574e+18,1131574142241726466,Press Release: Lufthansa accepts first A321neo...,"[0, 87]","<a href=""https://dlvrit.com/"" rel=""nofollow"">d...",False,NaN,None,NaN,...,1558623273798,NaN,False,NaN,NaN,NaN,NaN,NaN,"{'media': [{'id': 1131574140282892288, 'id_str...",NaN
14137,Thu May 23 14:54:40 +0000 2019,1.131574e+18,1131574168699457536,@MatthewFardell There will be staff to assist ...,"[16, 140]","<a href=""http://www.conversocial.com"" rel=""nof...",True,1.131570e+18,1131570086035300352,8.797686e+17,...,1558623280106,{'full_text': '@MatthewFardell There will be s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14138,Thu May 23 14:54:44 +0000 2019,1.131574e+18,1131574187569631232,RT @RoyalFamily: The Queen arrives at @British...,NaN,"<a href=""http://twitter.com/download/android"" ...",False,NaN,None,NaN,...,1558623284605,NaN,NaN,{'created_at': 'Thu May 23 10:28:34 +0000 2019...,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df2.to_excel(r'C:\Users\20203035\OneDrive - TU Eindhoven\Desktop\Real work\Year1-Q4\DBL challenge\dataframe2.xlsx', index=False)